name: Website Archive 2023
markdown: kramdown
url: https://mf-chan.com/webdev-archive-2023
permalink: /:categories/:slug

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

exclude:
  - generate/